// application/frontend/src/app/components/atoms/divider/divider.component.ts
import { Component, Input } from '@angular/core';

@Component({
  standalone: true,
  selector: 'app-divider',
  templateUrl: 'divider.component.html',
  styleUrls: ['divider.component.scss']
})
export class DividerComponent {
  @Input() public width: string = '0.25rem';
  @Input() public height: string = '2rem';

  public get styles(): Record<string, string> {
    return {
      width: this.width,
      height: this.height
    }
  }
}

<div class="container" [ngStyle]="this.getStyles()"></div>

// application/frontend/src/components/atoms/divider/divider.component.ts
import { LitElement, html, type TemplateResult, type CSSResultGroup, css } from 'lit';
import { customElement } from 'lit/decorators.js';

@customElement('app-divider')
export class DividerComponent extends LitElement {
  static override styles?: CSSResultGroup = css`
    .container {
      width: 0.025rem;
      height: 2rem;
      background-color: #000
    }
  `;

  public override render(): TemplateResult<1> {
    return html`<div class="container"></div>`;
  }
}
