// application/frontend/src/app/pages/landing/landing.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HeaderTypographyComponent } from '../../components/atoms/typography/header-typography/header-typography.component';
import { SubHeaderTypographyComponent } from '../../components/atoms/typography/sub-header-typography/sub-header-typography.component';
import { TypographyButtonComponent } from '../../components/molecules/buttons/typography-button/typography-button.component';
import { DividerComponent } from '../../components/atoms/divider/divider.component';

@Component({
  selector: 'app-landing',
  standalone: true,
  templateUrl: './landing.component.html',
  styleUrls: ['./landing.component.scss'],
  imports: [CommonModule, HeaderTypographyComponent, SubHeaderTypographyComponent, TypographyButtonComponent, DividerComponent]
})
export class LandingComponent {

}

<div class="container">
  <div class="container__inner">
    <div class="container__inner__typography">
      <app-header-typography [content]="'E-Bookler'"></app-header-typography>
      <app-sub-header-typography [content]="'Start monetizing your writting time!'"></app-sub-header-typography>
    </div>
    <app-divider [width]="'10rem'" [height]="'0.050rem'"></app-divider>
    <div class="container__inner__buttons">
      <app-typography-button [content]="'Sign In'"></app-typography-button>
      <app-typography-button [content]="'Sign Up'"></app-typography-button>
    </div>
  </div>
</div>

// application/frontend/src/pages/landing/landing.component.vue
<template>
  <div class="landing">
    <div class="landing__inner">
      <div class="landing__inner__box">
        <HeaderTypographyComponent :content="'E-Bookler'" />
        <SubHeaderTypographyComponent :content="'Monetize your writting time!'" />
      </div>
      <TypographyButtonComponent :content="'Getting Started'" />
    </div>
  </div>
</template>

<script setup lang="ts">
  import HeaderTypographyComponent from "@/components/atoms/typography/header-typography/header-typography.component.vue";
  import SubHeaderTypographyComponent from "@/components/atoms/typography/sub-header-typography/sub-header-typography.component.vue";
import TypographyButtonComponent from "@/components/molecules/buttons/typography-button/typography-button.component.vue";
</script>

<style lang="scss" scoped>
  .landing {
    height: 90vh;
    width: 100vw;
  }

  .landing__inner {
    height: inherit;
    width: inherit;

    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    gap: 1.5rem;
  }

  .landing__inner__box {
    display: flex;
    flex-direction: column;
    align-items: center;
    
    gap: 0.5rem;
  }
</style>
