// application/frontend/src/components/organisms/navbar/navbar.component.vue
<template>
    <div class="navbar">
        <div class="navbar__inner">
            <div class="navbar__inner group">
                <IconComponent name="menu" color="light" size="minimum"></IconComponent>
                <DividerComponent width="0.025rem" height="1.5rem"></DividerComponent>
                <TypographyComponent content="E-Bookler" :typography="'brand'"></TypographyComponent>
            </div>
            <div class="navbar__inner group">
                <IconComponent name="notification" color="light" size="minimum"></IconComponent>
                <IconComponent name="search" color="light" size="minimum"></IconComponent>
                <IconComponent name="settings" color="light" size="minimum"></IconComponent>
                <DividerComponent width="0.025rem" height="1.5rem"></DividerComponent>
                <IconComponent name="locale" color="light" size="minimum"></IconComponent>
                <IconComponent name="theme" color="light" size="minimum"></IconComponent>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import IconComponent from "./../../atoms/icon/icon.component.vue";
import DividerComponent from "./../../atoms/divider/divider.component.vue";
import TypographyComponent from "./../../atoms/typography/typography.component.vue";
</script>

<style scoped lang="scss">
    .navbar {
        width: 100vw;

        box-shadow: 0 0 1rem 0.50rem #1a1a1a;

        &__inner {
            padding: 0.5rem;

            display: flex;
            flex-direction: row;
            justify-content: space-between;
            align-items: center;

            &.group {
                display: flex;
                flex-direction: row;
                align-items: center;

                gap: 0.5rem;
            }
        }
    }
</style>

// application/frontend/src/components/organisms/navbar/navbar.component.ts
import { type CSSResultGroup, LitElement, css, html, type TemplateResult } from 'lit';
import { customElement } from 'lit/decorators.js';

@customElement('app-navbar')
export class NavbarComponent extends LitElement {
  static override styles?: CSSResultGroup = css`
    .container {
      box-shadow: 0px 0.5px 1.5px rgba(0, 0, 0, 0.25);
    }

    .container--inner {
      padding: 0.5rem;

      display: flex;
      flex-direction: row;
      align-items: center;
      justify-content: space-between;
    }

    .row {
      display: flex;
      flex-direction: row;
      gap: 0.5rem;
    }
  `;

  protected override render(): TemplateResult<1> {
    return html`
      <div class="container">
        <div class="container--inner">
          <div class="container--inner row">
            <app-hamburger-icon></app-hamburger-icon>
            <app-divider></app-divider>
            <app-brand-typography content="E-Bookler"></app-brand-typography>
          </div>
          <div class="container--inner row">
            <app-notification-icon></app-notification-icon>
            <app-search-icon></app-search-icon>
            <app-setting-icon></app-setting-icon>
            <app-divider></app-divider>
            <app-lightbulb-icon></app-lightbulb-icon>
            <app-locale-icon></app-locale-icon>
          </div>
        </div>
      </div>
    `;
  }
}
