// application/frontend/src/app/components/organisms/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { BrandTypographyComponent } from '../../atoms/typographies/brand/brand-typography.component';

@Component({
  standalone: true,
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss'],
  imports: [BrandTypographyComponent]
})
export class NavbarComponent {}

<div class="container">
  <div class="container__inner">
    <div class="container__inner column">
      <app-brand-typography [content]="'E-Bookler'"></app-brand-typography>
    </div>
    <div class="container__inner column"></div>
  </div>
</div>

// application/frontend/src/components/organisms/navbar/navbar.component.ts
import { LitElement, type TemplateResult, customElement, html } from 'lit-element';

@customElement('app-navbar')
export class NavbarComponent extends LitElement {
  public override render(): TemplateResult<1> {
    return html`
      <div class="container">
        <div class="container--inner">
          <app-brand-typography content="E-Bookler"></app-brand-typography>
        </div>
      </div>
    `;
  }
}
