// application/frontend/src/app/pages/authentication/sign-in/sign-in.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HeaderTypographyComponent } from '../../../components/atoms/typography/header-typography/header-typography.component';
import { SubHeaderTypographyComponent } from '../../../components/atoms/typography/sub-header-typography/sub-header-typography.component';
import { type FormComponentModel } from 'src/app/components/organisms/form/form.component.model';

@Component({
  selector: 'app-sign-in',
  standalone: true,
  templateUrl: './sign-in.component.html',
  styleUrls: ['./sign-in.component.scss'],
  imports: [CommonModule, HeaderTypographyComponent, SubHeaderTypographyComponent]
})
export class SignInComponent {
  private readonly formComponentModel: FormComponentModel;

  public constructor() {
    this.formComponentModel = { formActionCollection: [], formCategoryCollection: [] }
    this.defineFormCategoryCollection();
    this.defineFormActionCollection();
  }

  private defineFormCategoryCollection(): void {
    this.formComponentModel.formCategoryCollection.push(
      { name: 'Account Information', formCategoryFieldCollection: [{ name: 'accessCode', type: 'string', placeholder: 'Bookler Key', rules: ['required'] }] }
    )
  }

  private defineFormActionCollection(): void {
    this.formComponentModel.formActionCollection.push(
      { placeholder: 'SignIn Account', segment: 'button', callback: this.onSignInAction, redirectionRoute: '/dashboard' },
      { placeholder: 'Don’t have an account? Register here!', segment: 'link', redirectionRoute: '/sign-up' },
      { placeholder: 'Forgot your account data? Recover here!', segment: 'link', redirectionRoute: '/recover-access-code' }
    )
  }

  private onSignInAction(): void {}
}

<div class="container">
  <div class="container__inner">
    <app-header-typography [content]="'E-Bookler'"></app-header-typography>
    <app-sub-header-typography [content]="'Start monetizing your writting time!'"></app-sub-header-typography>
    <app-form
      [formFields]="this.getFormFields()"
      [formActions]="this.getFormActions()"
    ></app-form>
  </div>
</div>

// application/frontend/src/pages/sign-in.vue
<template>
    <div id="container">
        <Form :form-header="formHeader" :form-sections="formSections" :buttons="formButtons" :links="formLinks" :on-submit="onSubmit" />
    </div>
</template>

<script setup lang="ts">
import type { ButtonProps } from "@/components/atoms/button/Button.type";
import type { LinkProps } from "@/components/atoms/link/Link.type";
import type { FormHeaderProps } from "@/components/molecules/form-header/FormHeader.type";
import type { FormSectionProps } from "@/components/molecules/form-section/FormSection.type";
import Form from "@/components/organisms/form/Form.vue";
import { required } from '@vuelidate/validators'

const formHeader: FormHeaderProps = { header: 'E-Bookler', subHeader: 'Start typing on E-Bookler to monetize your content' }
const formSections: Array<FormSectionProps> = [{ designation: "Account Information", formControls: [{ name: 'accessCode', type: 'password', placeholder: 'Access Code...', rules: { required } }] }]
const formButtons: Array<ButtonProps> = [{ type: 'submit', content: 'Continue' }]
const formLinks: Array<LinkProps> = [{ content: 'No Account? Create one here!', href: "/sign-up" }, { content: 'Forgot AcessCode? Recover it here!', href: "/recover-access-code" }]
const onSubmit = () => {}

</script>

<style scoped lang="scss">
#container {
    min-height: 100vh;
}
</style>
