// application/frontend/src/components/organisms/navbar/navbar.component.ts
import { type CSSResultGroup, LitElement, css, html, type TemplateResult } from 'lit';
import { customElement } from 'lit/decorators.js';

@customElement('app-navbar')
export class NavbarComponent extends LitElement {
  static override styles?: CSSResultGroup = css`
    .container {
      min-height: 4rem;
    }

    .container--inner {
      min-height: inherit;

      padding: 0.5rem;

      display: flex;
      flex-direction: row;
      align-items: center;
      justify-content: space-between;
    }

    .row {
      display: flex;
      flex-direction: row;
      gap: 0.5rem;
    }
  `;

  protected override render(): TemplateResult<1> {
    return html`
      <div class="container">
        <div class="container--inner">
          <div class="container--inner row">
            <app-hamburger-icon></app-hamburger-icon>
            <app-divider></app-divider>
            <app-brand-typography content="E-Bookler"></app-brand-typography>
          </div>
          <div class="container--inner row">
            <app-notification-icon></app-notification-icon>
            <app-search-icon></app-search-icon>
            <app-setting-icon></app-setting-icon>
            <app-divider></app-divider>
            <app-lightbulb-icon></app-lightbulb-icon>
            <app-locale-icon></app-locale-icon>
          </div>
        </div>
      </div>
    `;
  }
}

// application/frontend/src/components/Navbar.vue
<template>
    <div id="navbar">
        <div id="navbar__inner">
            <Typography :content="'E-Bookler'" :segment="'brand'" />
            <div id="navbar__inner--search">
                <FormControl :name="'search'" :placeholder="'Search...'" :type="'text'" :rules="[]" :hide-alerts="true" />
            </div>
            <div id="navbar__inner--icons">
                <Icon :name="'dashboard'" :height="'1.25rem'" :width="'1.25rem'" />
                <Icon :name="'dossier'" :height="'1.25rem'" :width="'1.25rem'" :onClick="navigateToDossier" />
                <Icon :name="'settings'" :height="'1.25rem'" :width="'1.25rem'" />
                <Divider :width="'0.025rem'" :height="'2rem'" />
                <Icon :name="'locale'" :height="'1.25rem'" :width="'1.25rem'" />
                <Icon :name="'theme'" :height="'1.25rem'" :width="'1.25rem'" />
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router';
import Divider from './Divider.vue';
import FormControl from './FormControl.vue';
import Icon from './Icon.vue';
import Typography from './Typography.vue';
import { storeToRefs } from 'pinia';
import { useSession } from '@/stores/useSession';
const { push } = useRouter();
const { session } = storeToRefs(useSession());
const navigateToDossier = async () => await push({ name: "dossier", params: { userUuid: session.value?.userUuid} })
</script>

<style scoped lang="scss">
#navbar {
    height: 5rem;

    box-shadow: 0 0 0.05rem 0rem currentColor;

    &__inner {
        height: inherit;
        padding: 0 1.25rem;

        display: flex;
        flex-direction: row;
        justify-content: space-between;
        align-items: center;

        &--search {
            width: 100%;
            max-width: 35%;
        }

        @media(min-width:520px) {
            &--search {
                max-width: 50%;
            }
        }

        &--icons {
            display: flex;
            flex-direction: row;
            align-items: center;
            gap: 0.25rem;
        }
    }
}
</style>
