// application/frontend/src/pages/landing/landing.component.ts
import { type HTMLTemplateResult, LitElement, html, type CSSResultGroup, css } from 'lit';
import { customElement } from 'lit/decorators.js';

@customElement('app-landing')
export class LandingComponent extends LitElement {
  public static override styles?: CSSResultGroup | undefined = css`
    .container {
      min-height: 100vh;
    }

    .container__inner {
      min-height: inherit;

      padding: 0 2.5rem;

      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center; 

      gap: 2.5rem;
    }

    .container__inner__typography {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;

      text-align: center;
      
      gap: 1.5rem;
    }
  `;

  public override render(): HTMLTemplateResult {
    return html`
      <div class="container">
        <div class="container__inner">
          <div class="container__inner__typography">
            <app-header-typography 
              content="Welcome To E-Bookler"
            ></app-header-typography>
            <app-sub-header-typography 
              content="Our Platform. Your creative and original content. Start monetizing your writing time."
            ></app-sub-header-typography> 
          </div>
          <app-typography-button
            content="Getting Started"
          ></app-typography-button>
        </div>
      </div>
    `;
  }
}

// application/frontend/src/journeys/landing/landing.component.vue
<template>
  <div class="container">
    <div class="container__inner">
      <HeaderTypographyComponent :typography="'E-Bookler'" />
      <SubHeaderTypographyComponentVue :typography="'Our Platform. Your creativity. Monetize your content.'" />
    </div>
  </div>
</template>

<script setup lang="ts">
  import HeaderTypographyComponent from '@/components/atoms/typography/header-typography/header-typography.component.vue';
  import SubHeaderTypographyComponentVue from '@/components/atoms/typography/sub-header-typography/sub-header-typography.component.vue';
</script>

<style scoped lang="scss">
  .container {
    min-height: 100vh;
    width: 100vw;
  }

  .container__inner {
    min-height: inherit;
    width: inherit;

    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;

    text-align: center;

    gap: .5rem;
  }
</style>
