// application/frontend/src/app.component.vue
<template>
  <div class="wrapper">
    <router-view></router-view>
  </div>
</template>

<script setup lang="ts"></script>

<style lang="scss">
  @import url('https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap');
  
  * {
    padding: 0;
    margin: 0;
    box-sizing: border-box;

    font-family: 'Quicksand', sans-serif;

    --dark--primary--color: #343540;
    --dark--secondary--color: #131317;
    --light--primary--color: #FAFAFA;
  }

  html, body {
    min-height: 100vh;
    width: 100vw;
  }

  #app {
    min-height: inherit;
    width: inherit;
  }

  .wrapper {
    min-height: inherit;
    width: inherit;

    display: flex;
    flex-direction: column;
  }

  .darkTheme {
    background-color: var(--dark--primary--color);
    color: var(--light--primary--color);
  }

  .lightTheme {
    background-color: var(--light--primary--color);
    color: var(--dark--primary--color);
  }
</style>

// application/frontend/src/app.component.ts
import { LitElement, html, type TemplateResult, type CSSResultGroup, css } from 'lit';
import { customElement } from 'lit/decorators.js';

@customElement('app-component')
export class AppComponent extends LitElement {
  static override styles?: CSSResultGroup = css`
    @import url('https://fonts.googleapis.com/css2?family=Quicksand&display=swap');

    .container {
      min-height: 100vh;
      width: 100vw;

      font-family: 'Quicksand', sans-serif;
    }

    .container--inner {
      min-height: inherit;
      width: inherit;
    }

    .dark-theme {
      background-color: #343540;
      color: #fafafa;
    }

    .light-theme {
      background-color: #fafafa;
      color: #343540;
    }
  `;

  public override render(): TemplateResult<1> {
    return html`
      <div class="container light-theme">
        <div class="container--inner">
          <app-navbar></app-navbar>
        </div>
      </div>
    `;
  }
}
