// application/frontend/src/app.component.ts
import { LitElement, html, type TemplateResult, type CSSResultGroup, css } from 'lit';
import { customElement } from 'lit/decorators.js';

@customElement('app-component')
export class AppComponent extends LitElement {
  static override styles?: CSSResultGroup = css`
    @import url('https://fonts.googleapis.com/css2?family=Quicksand&display=swap');

    .container {
      min-height: 100vh;
      width: 100vw;

      font-family: 'Quicksand', sans-serif;
    }

    .container--inner {
      min-height: inherit;
      width: inherit;
    }

    .dark-theme {
      background-color: #343540;
      color: #fafafa;
    }

    .light-theme {
      background-color: #fafafa;
      color: #343540;
    }
  `;

  public override render(): TemplateResult<1> {
    return html`
      <div class="container light-theme">
        <div class="container--inner">
          <app-navbar></app-navbar>
        </div>
      </div>
    `;
  }
}

// application/frontend/src/App.vue
<template>
    <router-view></router-view>
</template>

<script setup lang="ts">
</script>

<style lang="scss">
@import url('https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap');

* {
  padding: 0;
  margin: 0;
  box-sizing: border-box;

  --dark--theme--color: #394053;
  --light--theme--color: #FFFFFF;

  background-color: var(--light--theme--color);
  color: var(--dark--theme--color);

  font-family: 'Quicksand', sans-serif;
}

html, body, #app {
  width: 100vw;
  min-height: 100vh;
}
</style>
