// application/frontend/src/app/pages/authentication/sign-in/sign-in.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HeaderTypographyComponent } from '../../../components/atoms/typography/header-typography/header-typography.component';
import { SubHeaderTypographyComponent } from '../../../components/atoms/typography/sub-header-typography/sub-header-typography.component';
import { type FormComponentModel } from 'src/app/components/organisms/form/form.component.model';

@Component({
  selector: 'app-sign-in',
  standalone: true,
  templateUrl: './sign-in.component.html',
  styleUrls: ['./sign-in.component.scss'],
  imports: [CommonModule, HeaderTypographyComponent, SubHeaderTypographyComponent]
})
export class SignInComponent {
  private readonly formComponentModel: FormComponentModel;

  public constructor() {
    this.formComponentModel = { formActionCollection: [], formCategoryCollection: [] }
    this.defineFormCategoryCollection();
    this.defineFormActionCollection();
  }

  private defineFormCategoryCollection(): void {
    this.formComponentModel.formCategoryCollection.push(
      { name: 'Account Information', formCategoryFieldCollection: [{ name: 'accessCode', type: 'string', placeholder: 'Bookler Key', rules: ['required'] }] }
    )
  }

  private defineFormActionCollection(): void {
    this.formComponentModel.formActionCollection.push(
      { placeholder: 'SignIn Account', segment: 'button', callback: this.onSignInAction, redirectionRoute: '/dashboard' },
      { placeholder: 'Don’t have an account? Register here!', segment: 'link', redirectionRoute: '/sign-up' },
      { placeholder: 'Forgot your account data? Recover here!', segment: 'link', redirectionRoute: '/recover-access-code' }
    )
  }

  private onSignInAction(): void {}
}

<div class="container">
  <div class="container__inner">
    <app-header-typography [content]="'E-Bookler'"></app-header-typography>
    <app-sub-header-typography [content]="'Start monetizing your writting time!'"></app-sub-header-typography>
    <app-form
      [formFields]="this.getFormFields()"
      [formActions]="this.getFormActions()"
    ></app-form>
  </div>
</div>

// application/frontend/src/pages/sign-in/sign-in.component.vue
<template>
    <div class="container">
        <div class="container--inner">
            <FormComponent :header="'E-Bookler'" :sub-header="'Start monetizing your writting time!'"
                :button-label="'Sign In To Account'" :button-action="signIn" :form-group-collection="formGroupCollection"
                :link-collection="linkCollection"></FormComponent>
            <DividerComponent :width="'100%'" :height="'0.05rem'"></DividerComponent>
        </div>
    </div>
</template>

<script setup lang="ts">
import { DividerComponent } from "../../components/atoms/divider";
import { FormGroupProps } from "../../components/molecules/form-group";
import { LinkProps } from "../../components/molecules/link";
import { FormComponent } from "./../../components/organisms/form";

const formGroupCollection = new Array<FormGroupProps>(
    {
        name: "Account Information",
        formControlCollection: [
            {
                type: 'password',
                placeholder: 'Bookler Key...'
            }
        ]
    }
);

const linkCollection = new Array<LinkProps>(
    {
        path: '/sign-up',
        content: 'Don’t have an account? Register here!'
    },
    {
        path: '/refresh-access-code',
        content: 'Forgot your account data? Recover here!'
    }
)

const signIn = () => { }
</script>

<style scoped lang="scss">
.container {
    width: 100vw;
    height: 100vh;
}
</style>
